const fs = require('fs');
const data = JSON.parse(fs.readFileSync('real_vehicles.json', 'utf8'));

let phpCode = '<?php\n';
phpCode += 'require __DIR__."/../vendor/autoload.php";\n';
phpCode += '$app = require_once __DIR__."/../bootstrap/app.php";\n';
phpCode += '$kernel = $app->make(Illuminate\\Contracts\\Console\\Kernel::class);\n';
phpCode += 'use Illuminate\\Support\\Facades\\DB;\n';
phpCode += 'try {\n';
phpCode += 'DB::statement("SET FOREIGN_KEY_CHECKS=0;");\n';
phpCode += 'DB::table("vehiculos")->truncate();\n';
phpCode += 'DB::table("mantenimientos")->truncate();\n';
phpCode += 'DB::table("lecturas_km")->truncate();\n';
phpCode += 'DB::statement("SET FOREIGN_KEY_CHECKS=1;");\n';
phpCode += '$jsonStr = \'' + JSON.stringify(data).replace(/'/g, "\\'") + '\';\n';
phpCode += '$data = json_decode($jsonStr, true);\n';
phpCode += '$imported = 0;\n';
phpCode += 'foreach($data as $v) {\n';
phpCode += '    $placa = trim($v["placa"]);\n';
phpCode += '    if(!$placa) continue;\n';
phpCode += '    $marca = !empty($v["marca"]) ? substr(trim($v["marca"]), 0, 255) : "N/A";\n';
phpCode += '    $modelo = !empty($v["modelo"]) ? trim($v["modelo"]) : "";\n';
phpCode += '    if(!empty($v["ano"])) $modelo .= " - " . $v["ano"];\n';
phpCode += '    if(!empty($v["color"])) $modelo .= " (" . $v["color"] . ")";\n';
phpCode += '    if(!$modelo) $modelo = "N/A";\n';
phpCode += '    $vin = !empty($v["vin"]) ? trim($v["vin"]) : null;\n';
phpCode += '    $estado = !empty($v["estado"]) ? strtolower(trim($v["estado"])) : "activo";\n';
phpCode += '    if(!in_array($estado, ["activo","taller","inactivo"])) $estado = "activo";\n';
phpCode += '    try {\n';
phpCode += '        DB::table("vehiculos")->insert([\n';
phpCode += '            "placa" => $placa,\n';
phpCode += '            "marca" => $marca,\n';
phpCode += '            "modelo" => $modelo,\n';
phpCode += '            "vin" => $vin,\n';
phpCode += '            "km_actual" => 0,\n';
phpCode += '            "km_proximo_mantenimiento" => 5000,\n';
phpCode += '            "estado" => $estado,\n';
phpCode += '            "created_at" => now(),\n';
phpCode += '            "updated_at" => now(),\n';
phpCode += '        ]);\n';
phpCode += '        $imported++;\n';
phpCode += '    } catch(\\Exception $e) {}\n';
phpCode += '}\n';
phpCode += 'echo "SUCCESS: Imported $imported vehicles.";\n';
phpCode += '} catch(\\Exception $e) { echo "ERROR: " . $e->getMessage(); }\n';

fs.writeFileSync('import_remote.php', phpCode);
console.log('import_remote.php created!');
